name: Playwright Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.ref != 'ref/head/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Install playwright dependencies
        run: bunx playwright install-deps chromium
      - name: Install browsers
        run: bunx playwright install --with-deps chromium
      - name: Run tests
        run: bunx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
